# Generated by Django 3.0.3 on 2020-08-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legislators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('tn', 'Tennessee')], max_length=2)),
                ('session', models.IntegerField()),
                ('bill_id', models.CharField(max_length=7)),
                ('action', models.TextField()),
                ('actor', models.CharField(choices=[('upper', 'Senate'), ('lower', 'House')], max_length=5)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('tn', 'Tennessee')], max_length=2)),
                ('session', models.IntegerField()),
                ('chamber', models.CharField(choices=[('upper', 'Senate'), ('lower', 'House')], max_length=5)),
                ('bill_id', models.CharField(max_length=7)),
                ('title', models.TextField()),
                ('scraped_subjects', models.CharField(max_length=200, null=True)),
                ('topics', models.CharField(max_length=200, null=True)),
                ('sponsors', models.ManyToManyField(to='legislators.Legislator')),
                ('subjects', models.ManyToManyField(to='bills.Subject')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(fields=('state', 'session', 'bill_id'), name='bill'),
        ),
    ]
