# Generated by Django 3.0.3 on 2020-09-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Tennessee', 'Tennessee')], max_length=9)),
                ('session', models.IntegerField()),
                ('name', models.CharField(max_length=7)),
                ('action', models.CharField(max_length=256)),
                ('actor', models.CharField(choices=[('ocd-organization/47760e16-8071-49dd-bd9f-354198c8b653', 'Senate'), ('ocd-organization/d4c442c8-d4d7-4ea9-a3fd-b856b2904d8b', 'House')], max_length=53)),
                ('classification', models.CharField(max_length=32)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('Tennessee', 'Tennessee')], max_length=9)),
                ('session', models.IntegerField()),
                ('chamber', models.CharField(choices=[('upper', 'Senate'), ('lower', 'House')], max_length=5)),
                ('name', models.CharField(max_length=7)),
                ('title', models.TextField()),
                ('scraped_subjects', models.CharField(max_length=200, null=True)),
                ('companion_name', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
            ],
        ),
    ]
