# Generated by Django 3.0.3 on 2020-09-05 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0001_initial'),
        ('legislators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='sponsors',
            field=models.ManyToManyField(to='legislators.Legislator'),
        ),
        migrations.AddField(
            model_name='bill',
            name='subjects',
            field=models.ManyToManyField(to='bills.Subject'),
        ),
        migrations.AddField(
            model_name='bill',
            name='topics',
            field=models.ManyToManyField(to='bills.Topic'),
        ),
        migrations.AddField(
            model_name='action',
            name='bill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.Bill'),
        ),
    ]
