# Generated by Django 3.0.3 on 2020-09-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legislator',
            fields=[
                ('legislator_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('given_name', models.CharField(max_length=50)),
                ('family_name', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('Tennessee', 'Tennessee')], max_length=9)),
                ('chamber', models.CharField(choices=[('upper', 'Senate'), ('lower', 'House')], max_length=5)),
                ('district', models.IntegerField(null=True)),
                ('party', models.CharField(choices=[('Democratic', 'Democratic'), ('Republican', 'Republican')], max_length=10)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Tennessee', 'Tennessee')], max_length=9)),
                ('option', models.CharField(choices=[('No', 'no'), ('Present', 'not voting'), ('Yes', 'yes')], max_length=10)),
                ('bill_id', models.ManyToManyField(to='bills.Bill')),
                ('legislator_id', models.ManyToManyField(to='legislators.Legislator')),
            ],
        ),
    ]
