# Generated by Django 3.0.3 on 2020-08-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Legislator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg_id', models.CharField(max_length=16)),
                ('full_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('suffix', models.CharField(max_length=50)),
                ('active', models.BooleanField()),
                ('state', models.CharField(max_length=2)),
                ('chamber', models.CharField(choices=[('upper', 'Senate'), ('lower', 'House')], max_length=5)),
                ('district', models.IntegerField(null=True)),
                ('party', models.CharField(choices=[('Democratic', 'Democratic'), ('Republican', 'Republican')], max_length=10)),
                ('photo_url', models.CharField(max_length=200)),
            ],
        ),
    ]
